from tests.end2end.e2e_case import E2ECase
from tests.end2end.end2end_test_setup import End2EndTestSetup
from tests.end2end.helpers.screens.project_index.screen_project_index import (
    Screen_ProjectIndex,
)
from tests.end2end.server import SDocTestServer


class Test(E2ECase):
    """
    E2E Test: Verifies that when a document is fully autogenerated
    (e.g., from a JUnit XML report), all structural UI actions are visually
    and functionally disabled via the ActionPolicy.
    """

    def test_autogenerated_document_ui_is_locked(self):
        test_setup = End2EndTestSetup(path_to_test_file=__file__)

        with SDocTestServer(
            input_path=test_setup.path_to_sandbox
        ) as test_server:
            self.open(test_server.get_host_and_port())

            # Navigate to the project index
            screen_project_index = Screen_ProjectIndex(self)
            screen_project_index.assert_on_screen()

            screen_document = screen_project_index.do_click_on_first_document()
            screen_document.assert_on_screen_document()

            screen_document.assert_document_config_edit_is_locked()

            node = screen_document.get_node()
            node.assert_add_action_is_locked()
            node.assert_edit_node_action_is_locked()
            node.assert_clone_node_action_is_locked()
            node.assert_delete_node_action_is_locked()

            screen_document.assert_first_toc_node_is_not_draggable()
