version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
    groups:
      github-actions:
        patterns: ["*"]
    commit-message:
      prefix: chore
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: friday
    allow:
      - dependency-type: development
    groups:
      python-packages:
        patterns: ["*"]
    commit-message:
      prefix: chore
