exceptions:
  - url: https://www.bugseng.com/blog/requirement-traceability-all-substance-and-no-fuss
    code: CONNECTION_ERROR
  - url: https://www.bugseng.com/blog/requirement-traceability-all-substance-and-no-fuss
    code: HTTP_403
