"""
@relation(SDOC-SRS-143, scope=file)

The cargo-nextest JUnit XML in these tests is taken from real cargo-nextest
output, not hand-written. The crate that produces every shape used below
(passing, failing, nested-module, integration-binary and multi-suite) lives in
tests/integration/features/test_reports/junit_xml/nextest/_generator/, and its
committed reports/junit.xml is regenerated by that directory's regenerate.sh.
The snippets here are minimal single-scenario slices of that output with the
run-specific fields (uuid, timestamps, durations, panic thread-id) normalized;
see nextest/README.md.
"""

import os
import tempfile

from strictdoc.backend.sdoc.models.document import SDocDocument
from strictdoc.backend.sdoc.models.node import SDocNode
from strictdoc.backend.sdoc_source_code.test_reports.junit_xml_reader import (
    JUnitXMLReader,
)
from strictdoc.core.file_system.file_tree import File
from strictdoc.core.project_config import ProjectConfig
from strictdoc.helpers.cast import assert_cast
from strictdoc.helpers.paths import SDocRelativePath


def test_01_passed_testcase():
    source_input = """\
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="nextest-run" tests="1" failures="0" errors="0" uuid="00000000-0000-0000-0000-000000000000" timestamp="2025-03-10T10:30:39+00:00" time="0.013">
    <testsuite name="my_crate" tests="1" disabled="0" errors="0" failures="0">
        <testcase name="tests::add_works" classname="my_crate" timestamp="2025-03-10T10:30:39+00:00" time="0.009">
        </testcase>
    </testsuite>
</testsuites>
"""

    project_config: ProjectConfig = ProjectConfig.default_config()

    with tempfile.NamedTemporaryFile(
        mode="w+", delete=True, suffix=".nextest.junit.xml"
    ) as temp_file:
        doc_file: File = File(
            0,
            temp_file.name,
            SDocRelativePath(os.path.basename(temp_file.name)),
        )
        document: SDocDocument = JUnitXMLReader.read_from_string(
            source_input, doc_file, project_config
        )
        assert len(document.section_contents) == 1
        assert len(document.section_contents[0].section_contents) == 2

        test_result_node: SDocNode = assert_cast(
            document.section_contents[0].section_contents[1], SDocNode
        )
        assert (
            test_result_node.get_meta_field_value_by_title("UID")
            == "my_crate::tests::add_works"
        )
        assert (
            test_result_node.get_meta_field_value_by_title("TITLE")
            == "my_crate::tests::add_works"
        )
        assert (
            test_result_node.get_meta_field_value_by_title("TEST_FUNCTION")
            == "#NEXTEST#my_crate|tests::add_works"
        )
        assert (
            test_result_node.get_meta_field_value_by_title("STATUS") == "PASSED"
        )


def test_02_failed_testcase():
    source_input = """\
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="nextest-run" tests="1" failures="1" errors="0" uuid="00000000-0000-0000-0000-000000000000" timestamp="2025-03-10T10:30:39+00:00" time="0.000">
    <testsuite name="my_crate" tests="1" disabled="0" errors="0" failures="1">
        <testcase name="tests::fails_on_purpose" classname="my_crate" timestamp="2025-03-10T10:30:39+00:00" time="0.000">
            <failure message="thread &apos;tests::fails_on_purpose&apos; panicked at src/lib.rs:16:9" type="test failure with exit code 101">thread &apos;tests::fails_on_purpose&apos; panicked at src/lib.rs:16:9:
assertion `left == right` failed
  left: 2
 right: 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace</failure>
            <system-out>
running 1 test
test tests::fails_on_purpose ... FAILED

failures:

failures:
    tests::fails_on_purpose

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.00s

</system-out>
            <system-err>
thread &apos;tests::fails_on_purpose&apos; panicked at src/lib.rs:16:9:
assertion `left == right` failed
  left: 2
 right: 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</system-err>
        </testcase>
    </testsuite>
</testsuites>
"""

    project_config: ProjectConfig = ProjectConfig.default_config()

    with tempfile.NamedTemporaryFile(
        mode="w+", delete=True, suffix=".nextest.junit.xml"
    ) as temp_file:
        doc_file: File = File(
            0,
            temp_file.name,
            SDocRelativePath(os.path.basename(temp_file.name)),
        )
        document: SDocDocument = JUnitXMLReader.read_from_string(
            source_input, doc_file, project_config
        )

        test_result_node: SDocNode = assert_cast(
            document.section_contents[0].section_contents[1], SDocNode
        )
        assert (
            test_result_node.get_meta_field_value_by_title("STATUS") == "FAILED"
        )
        assert (
            test_result_node.get_meta_field_value_by_title("TEST_FUNCTION")
            == "#NEXTEST#my_crate|tests::fails_on_purpose"
        )


def test_03_nested_module_test_uses_leaf_function_name():
    source_input = """\
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="nextest-run" tests="1" failures="0" errors="0" uuid="00000000-0000-0000-0000-000000000000" timestamp="2025-03-10T10:30:39+00:00" time="0.013">
    <testsuite name="my_crate" tests="1" disabled="0" errors="0" failures="0">
        <testcase name="tests::nested::nested_module_test" classname="my_crate" timestamp="2025-03-10T10:30:39+00:00" time="0.009">
        </testcase>
    </testsuite>
</testsuites>
"""

    project_config: ProjectConfig = ProjectConfig.default_config()

    with tempfile.NamedTemporaryFile(
        mode="w+", delete=True, suffix=".nextest.junit.xml"
    ) as temp_file:
        doc_file: File = File(
            0,
            temp_file.name,
            SDocRelativePath(os.path.basename(temp_file.name)),
        )
        document: SDocDocument = JUnitXMLReader.read_from_string(
            source_input, doc_file, project_config
        )

        test_result_node: SDocNode = assert_cast(
            document.section_contents[0].section_contents[1], SDocNode
        )
        assert (
            test_result_node.get_meta_field_value_by_title("UID")
            == "my_crate::tests::nested::nested_module_test"
        )
        assert (
            test_result_node.get_meta_field_value_by_title("TEST_FUNCTION")
            == "#NEXTEST#my_crate|tests::nested::nested_module_test"
        )


def test_04_integration_test_binary_uses_classname_with_double_colon():
    source_input = """\
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="nextest-run" tests="1" failures="0" errors="0" uuid="00000000-0000-0000-0000-000000000000" timestamp="2025-03-10T10:30:39+00:00" time="0.013">
    <testsuite name="my_crate::integration" tests="1" disabled="0" errors="0" failures="0">
        <testcase name="integration_add" classname="my_crate::integration" timestamp="2025-03-10T10:30:39+00:00" time="0.009">
        </testcase>
    </testsuite>
</testsuites>
"""

    project_config: ProjectConfig = ProjectConfig.default_config()

    with tempfile.NamedTemporaryFile(
        mode="w+", delete=True, suffix=".nextest.junit.xml"
    ) as temp_file:
        doc_file: File = File(
            0,
            temp_file.name,
            SDocRelativePath(os.path.basename(temp_file.name)),
        )
        document: SDocDocument = JUnitXMLReader.read_from_string(
            source_input, doc_file, project_config
        )

        test_result_node: SDocNode = assert_cast(
            document.section_contents[0].section_contents[1], SDocNode
        )
        assert (
            test_result_node.get_meta_field_value_by_title("UID")
            == "my_crate::integration::integration_add"
        )
        assert (
            test_result_node.get_meta_field_value_by_title("TEST_FUNCTION")
            == "#NEXTEST#my_crate::integration|integration_add"
        )


def test_05_multiple_testsuites_one_per_binary():
    source_input = """\
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="nextest-run" tests="2" failures="0" errors="0" uuid="00000000-0000-0000-0000-000000000000" timestamp="2025-03-10T10:30:39+00:00" time="0.013">
    <testsuite name="my_crate" tests="1" disabled="0" errors="0" failures="0">
        <testcase name="tests::add_works" classname="my_crate" timestamp="2025-03-10T10:30:39+00:00" time="0.009">
        </testcase>
    </testsuite>
    <testsuite name="my_crate::integration" tests="1" disabled="0" errors="0" failures="0">
        <testcase name="integration_add" classname="my_crate::integration" timestamp="2025-03-10T10:30:39+00:00" time="0.009">
        </testcase>
    </testsuite>
</testsuites>
"""

    project_config: ProjectConfig = ProjectConfig.default_config()

    with tempfile.NamedTemporaryFile(
        mode="w+", delete=True, suffix=".nextest.junit.xml"
    ) as temp_file:
        doc_file: File = File(
            0,
            temp_file.name,
            SDocRelativePath(os.path.basename(temp_file.name)),
        )
        document: SDocDocument = JUnitXMLReader.read_from_string(
            source_input, doc_file, project_config
        )
        assert len(document.section_contents) == 2
