# tests/unit/export/html/test_action_policy.py

from strictdoc.export.html.action_policy import ActionPolicy
from tests.unit.helpers.document_builder import DocumentBuilder

# Document Level Actions --------------------------------------------


def test_standard_document_can_be_edited():
    """A normal document should be fully interactive."""
    builder = DocumentBuilder()
    doc = builder.build()

    assert ActionPolicy.can_edit_document(doc) is True


def test_autogenerated_document_is_locked():
    """An autogenerated document should be locked."""

    builder = DocumentBuilder()
    doc = builder.build()
    doc.autogen = True

    assert ActionPolicy.can_edit_document(doc) is False


# Node Level Actions --------------------------------------------


def test_standard_node_allows_all_actions():
    """A normal node in a normal document should be fully interactive."""
    builder = DocumentBuilder()
    doc = builder.build()
    node = builder.add_requirement("REQ-1")

    assert ActionPolicy.can_edit_node(node, doc) is True
    assert ActionPolicy.can_add_node(node, doc) is True
    assert ActionPolicy.can_delete_node(node, doc) is True
    assert ActionPolicy.can_clone_node(node, doc) is True
    assert ActionPolicy.can_move_node(node, doc) is True


def test_pure_autogenerated_document_locks_all_nodes():
    """If the document is a test report, no node actions are permitted."""
    builder = DocumentBuilder()
    doc = builder.build()
    doc.autogen = True
    node = builder.add_requirement("REQ-1")
    node.autogen = True

    assert ActionPolicy.can_edit_node(node, doc) is False
    assert ActionPolicy.can_add_node(node, doc) is False
    assert ActionPolicy.can_delete_node(node, doc) is False
    assert ActionPolicy.can_clone_node(node, doc) is False
    assert ActionPolicy.can_move_node(node, doc) is False


def test_merged_node_from_source_code_protects_source_link_but_allows_edits():
    """
    A node exists in the .sdoc, but its text comes from source-code.
    It must allow edits (for non-merged fields), node moves, and adding children,
    but block deletion/cloning.
    """
    builder = DocumentBuilder()
    doc = builder.build()
    node = builder.add_requirement("REQ-1")

    # Simulate a merged node.
    # We grab an actual generated field and override its origin check.
    statement_field = node.ordered_fields_lookup["STATEMENT"][0]
    statement_field.is_document_origin = lambda: False

    # mark the UID field as source-origin
    uid_field = node.ordered_fields_lookup["UID"][0]
    uid_field.is_document_origin = lambda: False

    # Allowed Actions
    assert ActionPolicy.can_edit_node(node, doc) is True
    assert ActionPolicy.can_add_node(node, doc) is True
    assert ActionPolicy.can_move_node(node, doc) is True

    # Blocked Actions
    assert ActionPolicy.can_delete_node(node, doc) is False
    assert ActionPolicy.can_clone_node(node, doc) is False
    assert ActionPolicy.can_edit_field(uid_field) is False


# Field Level Actions --------------------------------------------


def test_standard_document_field_is_editable():
    """A normal field of a normal node in a normal document can be edited."""
    builder = DocumentBuilder()
    builder.build()
    node = builder.add_requirement("REQ-1")

    # Extract a real AST field directly from the native node
    statement_field = node.ordered_fields_lookup["STATEMENT"][0]

    assert ActionPolicy.can_edit_field(statement_field) is True


def test_source_managed_field_is_locked():
    """A field whose text was merged from a source-file cannot be edited."""
    builder = DocumentBuilder()
    builder.build()
    node = builder.add_requirement("REQ-1")

    # Extract a real AST field
    statement_field = node.ordered_fields_lookup["STATEMENT"][0]

    # Simulate the source-merge behavior natively by overriding the check
    statement_field.is_document_origin = lambda: False

    assert ActionPolicy.can_edit_field(statement_field) is False
