import pytest

from strictdoc.backend.sdoc.document_reference import DocumentReference
from strictdoc.backend.sdoc.models.grammar_element import GrammarElement
from strictdoc.backend.sdoc.models.node import SDocNodeField
from strictdoc.core.document_tree import DocumentTree
from strictdoc.core.traceability_index import TraceabilityIndex
from strictdoc.core.traceability_index_builder import TraceabilityIndexBuilder
from strictdoc.core.transforms.constants import NodeCreationOrder
from strictdoc.core.transforms.move_node_across_documents import (
    MoveNodeAcrossDocumentsCommand,
)
from strictdoc.core.transforms.validation_error import SingleValidationError
from tests.unit.helpers.document_builder import DocumentBuilder


def _build_two_document_index(
    doc1_requirements=("REQ-001",), doc2_requirements=("REQ-002",)
):
    document_builder_1 = DocumentBuilder("DOC-1")
    doc1_reqs = [
        document_builder_1.add_requirement(uid_) for uid_ in doc1_requirements
    ]
    document_1 = document_builder_1.build()

    document_builder_2 = DocumentBuilder("DOC-2")
    doc2_reqs = [
        document_builder_2.add_requirement(uid_) for uid_ in doc2_requirements
    ]
    document_2 = document_builder_2.build()

    # DocumentBuilder.add_requirement() only sets ng_document_reference.
    # can_move_node()/get_parent_or_including_document() also require
    # ng_including_document_reference to be a (possibly empty) reference,
    # same as every requirement built through the normal parser/reader path.
    for requirement_ in doc1_reqs + doc2_reqs:
        requirement_.ng_including_document_reference = DocumentReference()

    document_tree = DocumentTree(
        file_tree=[],
        document_list=[document_1, document_2],
        map_docs_by_paths={},
        map_docs_by_rel_paths={},
        map_grammars_by_filenames={},
    )
    traceability_index: TraceabilityIndex = (
        TraceabilityIndexBuilder.create_from_document_tree(
            document_tree, project_config=document_builder_1.project_config
        )
    )
    return traceability_index, document_1, doc1_reqs, document_2, doc2_reqs


def test_can_move_node_across_documents_true_for_plain_node():
    # Baseline: an ordinary node has no reason to be blocked from moving.
    # Without this, a bug that made the check always return False would
    # pass unnoticed alongside the negative cases below.
    traceability_index, _, requirements, _, _ = _build_two_document_index()
    assert traceability_index.can_move_node_across_documents(requirements[0])


def test_can_move_node_across_documents_false_for_node_with_image():
    # task.md disables Move for nodes with an inserted image because image
    # paths are not recalculated. Catches a check that forgets to scan node
    # content for image markup.
    traceability_index, _, requirements, _, _ = _build_two_document_index()
    requirement = requirements[0]
    requirement.set_field_value(
        field_name="STATEMENT",
        form_field_index=0,
        value="See the diagram: .. image:: diagram.png",
    )
    assert not traceability_index.can_move_node_across_documents(requirement)


def test_can_move_node_across_documents_false_for_subtree_with_image():
    traceability_index, document_1, requirements, _, _ = (
        _build_two_document_index(
            doc1_requirements=("REQ-001", "REQ-002"),
            doc2_requirements=("REQ-003",),
        )
    )
    moved_composite, child_with_image = requirements
    moved_composite.is_composite = True
    document_1.section_contents.remove(child_with_image)
    moved_composite.section_contents.append(child_with_image)
    child_with_image.parent = moved_composite
    child_with_image.set_field_value(
        field_name="STATEMENT",
        form_field_index=0,
        value="See the diagram: .. image:: diagram.png",
    )

    assert not traceability_index.can_move_node_across_documents(
        moved_composite
    )


def test_can_move_node_across_documents_false_for_autogenerated_node():
    # Move must respect the existing autogenerated-content restriction.
    # Catches a check that only looks at image content and skips the
    # underlying can_move_node() delegation.
    traceability_index, _, requirements, _, _ = _build_two_document_index()
    requirement = requirements[0]
    requirement.autogen = True
    assert not traceability_index.can_move_node_across_documents(requirement)


def test_can_move_node_across_documents_false_for_autogenerated_subtree():
    traceability_index, document_1, requirements, _, _ = (
        _build_two_document_index(
            doc1_requirements=("REQ-001", "REQ-002"),
            doc2_requirements=("REQ-003",),
        )
    )
    moved_composite, autogenerated_child = requirements
    moved_composite.is_composite = True
    document_1.section_contents.remove(autogenerated_child)
    moved_composite.section_contents.append(autogenerated_child)
    autogenerated_child.parent = moved_composite
    autogenerated_child.autogen = True

    assert traceability_index.subtree_has_autogenerated_content(moved_composite)
    assert not traceability_index.can_move_node_across_documents(
        moved_composite
    )


def test_is_node_in_own_subtree_true_for_self():
    # Base case for the "cannot move a node into itself" validation: a
    # node's own subtree always contains itself.
    traceability_index, _, requirements, _, _ = _build_two_document_index()
    requirement = requirements[0]
    assert traceability_index.is_node_in_own_subtree(requirement, requirement)


def test_is_node_in_own_subtree_false_for_unrelated_node():
    # Negative case for the same check: an unrelated node in a different
    # document must not be flagged as an invalid target. Guards against an
    # overly broad implementation that rejects every cross-document move.
    traceability_index, _, doc1_reqs, _, doc2_reqs = _build_two_document_index()
    assert not traceability_index.is_node_in_own_subtree(
        doc1_reqs[0], doc2_reqs[0]
    )


def test_move_node_across_documents_updates_document_reference_and_files():
    # End-to-end shape of a cross-document move: node leaves the source
    # document's tree, lands in the destination's tree at the right
    # position, and command.source_document/destination_document (which
    # the router uses to decide which .sdoc files to write) are correct.
    traceability_index, document_1, doc1_reqs, document_2, doc2_reqs = (
        _build_two_document_index()
    )
    moved_requirement = doc2_reqs[0]
    target_requirement = doc1_reqs[0]

    assert moved_requirement.get_document() is document_2
    assert moved_requirement in document_2.section_contents
    assert moved_requirement not in document_1.section_contents

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=moved_requirement,
        target_node=target_requirement,
        whereto=NodeCreationOrder.AFTER,
        traceability_index=traceability_index,
    )
    command.perform()

    # The moved node (and, transitively, its subtree) now belongs to the
    # destination document. This is the assertion that would catch a missed
    # ng_document_reference update.
    assert moved_requirement.get_document() is document_1
    assert moved_requirement.parent is document_1

    assert moved_requirement not in document_2.section_contents
    assert document_1.section_contents == [
        target_requirement,
        moved_requirement,
    ]

    assert command.source_document is document_2
    assert command.destination_document is document_1


def test_move_node_into_empty_document():
    traceability_index, document_1, doc1_reqs, document_2, _ = (
        _build_two_document_index(doc2_requirements=())
    )
    moved_requirement = doc1_reqs[0]

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=moved_requirement,
        target_node=document_2,
        whereto=NodeCreationOrder.CHILD,
        traceability_index=traceability_index,
    )
    command.perform()

    assert document_1.section_contents == []
    assert document_2.section_contents == [moved_requirement]
    assert moved_requirement.parent is document_2
    assert moved_requirement.get_document() is document_2


def test_move_node_as_last_child_of_composite_node():
    traceability_index, document_1, doc1_reqs, _, doc2_reqs = (
        _build_two_document_index(
            doc1_requirements=("REQ-001", "REQ-002"),
            doc2_requirements=("REQ-003",),
        )
    )
    moved_requirement = doc2_reqs[0]
    composite_requirement, existing_child = doc1_reqs
    composite_requirement.is_composite = True
    document_1.section_contents.remove(existing_child)
    composite_requirement.section_contents.append(existing_child)
    existing_child.parent = composite_requirement

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=moved_requirement,
        target_node=composite_requirement,
        whereto=NodeCreationOrder.CHILD,
        traceability_index=traceability_index,
    )
    command.perform()

    assert composite_requirement.section_contents == [
        existing_child,
        moved_requirement,
    ]
    assert moved_requirement.parent is composite_requirement


def test_move_node_as_child_of_non_composite_node_is_rejected():
    traceability_index, _, doc1_reqs, _, doc2_reqs = _build_two_document_index()

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=doc1_reqs[0],
        target_node=doc2_reqs[0],
        whereto=NodeCreationOrder.CHILD,
        traceability_index=traceability_index,
    )

    with pytest.raises(SingleValidationError):
        command.perform()


# Regression test: SDocParsingProcessor.process_requirement() assigns every
# node of a document the SAME DocumentReference instance (by reference, not
# a copy), see strictdoc/backend/sdoc/processor.py. An earlier version of
# MoveNodeAcrossDocumentsCommand called
# moved_node.ng_document_reference.set_document(destination) directly,
# which mutated that shared instance in place and silently repointed every
# other, untouched node of the source document to the destination too.
# DocumentBuilder gives each node its own DocumentReference instance, so it
# does not reproduce this sharing; the test below simulates it explicitly.
def test_move_node_across_documents_does_not_corrupt_sibling_document_reference():
    traceability_index, document_1, doc1_reqs, _, doc2_reqs = (
        _build_two_document_index(
            doc1_requirements=("REQ-001", "REQ-002"),
            doc2_requirements=("REQ-003",),
        )
    )
    moved_requirement, sibling_requirement = doc1_reqs
    target_requirement = doc2_reqs[0]

    shared_reference = DocumentReference()
    shared_reference.set_document(document_1)
    moved_requirement.ng_document_reference = shared_reference
    sibling_requirement.ng_document_reference = shared_reference

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=moved_requirement,
        target_node=target_requirement,
        whereto=NodeCreationOrder.AFTER,
        traceability_index=traceability_index,
    )
    command.perform()

    assert moved_requirement.get_document() is command.destination_document
    # The sibling shared the same DocumentReference instance before the
    # move and must still resolve to the source document afterward.
    assert sibling_requirement.get_document() is document_1


def test_move_node_within_same_document_reorders_without_reference_change():
    # The same modal flow also handles reordering within one document
    # (task.md: "before"/"after" any node at any level, same document or
    # not). This must behave like a plain reorder: no document_reference
    # rewrite, and source_document/destination_document both point at the
    # one document, so the router does not write it twice.
    traceability_index, document_1, doc1_reqs, _, _ = _build_two_document_index(
        doc1_requirements=("REQ-001", "REQ-002"),
        doc2_requirements=("REQ-003",),
    )
    first_requirement, second_requirement = doc1_reqs

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=first_requirement,
        target_node=second_requirement,
        whereto=NodeCreationOrder.AFTER,
        traceability_index=traceability_index,
    )
    command.perform()

    assert first_requirement.get_document() is document_1
    assert document_1.section_contents == [
        second_requirement,
        first_requirement,
    ]
    assert command.source_document is document_1
    assert command.destination_document is document_1


@pytest.mark.parametrize(
    "whereto",
    [
        NodeCreationOrder.BEFORE,
        NodeCreationOrder.AFTER,
        NodeCreationOrder.CHILD,
    ],
)
def test_move_node_already_at_target_location_is_no_op(whereto: str):
    traceability_index, document_1, doc1_reqs, _, _ = _build_two_document_index(
        doc1_requirements=("REQ-001", "REQ-002"),
        doc2_requirements=("REQ-003",),
    )
    first_requirement, second_requirement = doc1_reqs

    if whereto == NodeCreationOrder.BEFORE:
        moved_requirement = first_requirement
        target_node = second_requirement
    elif whereto == NodeCreationOrder.AFTER:
        moved_requirement = second_requirement
        target_node = first_requirement
    else:
        first_requirement.is_composite = True
        document_1.section_contents.remove(second_requirement)
        first_requirement.section_contents.append(second_requirement)
        second_requirement.parent = first_requirement
        moved_requirement = second_requirement
        target_node = first_requirement

    parent_contents_before_move = list(
        moved_requirement.parent.section_contents
    )
    last_updated_before_move = traceability_index.index_last_updated
    command = MoveNodeAcrossDocumentsCommand(
        moved_node=moved_requirement,
        target_node=target_node,
        whereto=whereto,
        traceability_index=traceability_index,
    )

    command.perform()

    assert not command.move_was_performed
    assert moved_requirement.parent.section_contents == (
        parent_contents_before_move
    )
    assert traceability_index.index_last_updated == last_updated_before_move


def test_move_node_into_own_subtree_raises_validation_error():
    # task.md requires blocking a move into the node's own subtree; the
    # modal's UI hides the links for this case, but the backend must
    # reject it independently rather than relying on the UI alone.
    traceability_index, _, requirements, _, _ = _build_two_document_index()
    requirement = requirements[0]

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=requirement,
        target_node=requirement,
        whereto=NodeCreationOrder.AFTER,
        traceability_index=traceability_index,
    )
    with pytest.raises(SingleValidationError):
        command.perform()


# Regression test: moving a node whose type belongs to a custom grammar
# element (e.g. "FEATURE", as used by StrictDoc's own docs) into a document
# whose grammar does not define that element type used to crash rendering
# with a KeyError in get_requirement_style_mode() instead of being rejected
# up front.
def test_move_node_with_incompatible_grammar_type_raises_validation_error():
    traceability_index, document_1, doc1_reqs, document_2, doc2_reqs = (
        _build_two_document_index()
    )
    moved_requirement = doc1_reqs[0]
    moved_requirement.node_type = "FEATURE"
    assert document_1.grammar is not None
    document_1.grammar.elements_by_type["FEATURE"] = (
        GrammarElement.create_default("FEATURE")
    )
    # document_2's grammar (default) does not define "FEATURE".

    target_requirement = doc2_reqs[0]

    assert not traceability_index.is_move_grammar_compatible(
        moved_requirement, document_2
    )

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=moved_requirement,
        target_node=target_requirement,
        whereto=NodeCreationOrder.AFTER,
        traceability_index=traceability_index,
    )
    with pytest.raises(SingleValidationError):
        command.perform()

    # The rejected move must not have mutated the tree.
    assert moved_requirement in document_1.section_contents
    assert moved_requirement not in document_2.section_contents


def test_move_node_rejects_field_missing_from_destination_grammar():
    traceability_index, _, doc1_reqs, document_2, doc2_reqs = (
        _build_two_document_index()
    )
    moved_requirement = doc1_reqs[0]
    moved_requirement.ordered_fields_lookup["CUSTOM_FIELD"] = [
        SDocNodeField.create_from_string(
            parent=moved_requirement,
            field_name="CUSTOM_FIELD",
            field_value="custom value",
            multiline=False,
        )
    ]

    assert not traceability_index.is_move_grammar_compatible(
        moved_requirement, document_2
    )

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=moved_requirement,
        target_node=doc2_reqs[0],
        whereto=NodeCreationOrder.AFTER,
        traceability_index=traceability_index,
    )
    with pytest.raises(SingleValidationError):
        command.perform()


def test_move_node_rejects_destination_grammar_without_mid_field():
    traceability_index, _, doc1_reqs, document_2, doc2_reqs = (
        _build_two_document_index()
    )
    moved_requirement = doc1_reqs[0]
    moved_requirement.ordered_fields_lookup["MID"] = [
        SDocNodeField.create_from_string(
            parent=moved_requirement,
            field_name="MID",
            field_value=str(moved_requirement.reserved_mid),
            multiline=False,
        )
    ]
    moved_requirement.ordered_fields_lookup.move_to_end("MID", last=False)

    assert document_2.config.enable_mid is not True
    assert not traceability_index.is_move_grammar_compatible(
        moved_requirement, document_2
    )

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=moved_requirement,
        target_node=doc2_reqs[0],
        whereto=NodeCreationOrder.AFTER,
        traceability_index=traceability_index,
    )
    with pytest.raises(SingleValidationError):
        command.perform()

    assert "MID" in moved_requirement.ordered_fields_lookup


def test_move_node_with_compatible_grammar_type_within_same_document():
    # Counterpart to the incompatible-grammar test above: the grammar
    # check must not false-positive and block an ordinary same-document
    # reorder just because the node's type happens to be a custom one.
    traceability_index, document_1, doc1_reqs, _, _ = _build_two_document_index(
        doc1_requirements=("REQ-001", "REQ-002"),
        doc2_requirements=("REQ-003",),
    )
    moved_requirement, target_requirement = doc1_reqs
    moved_requirement.node_type = "FEATURE"
    assert document_1.grammar is not None
    document_1.grammar.elements_by_type["FEATURE"] = (
        GrammarElement.create_default("FEATURE")
    )

    # A node is always grammar-compatible with its own document.
    assert traceability_index.is_move_grammar_compatible(
        moved_requirement, document_1
    )

    command = MoveNodeAcrossDocumentsCommand(
        moved_node=moved_requirement,
        target_node=target_requirement,
        whereto=NodeCreationOrder.AFTER,
        traceability_index=traceability_index,
    )
    command.perform()

    assert document_1.section_contents == [
        target_requirement,
        moved_requirement,
    ]
