from enum import Enum, IntEnum


class GraphLinkType(IntEnum):
    MID_TO_NODE = 1
    UID_TO_NODE = 2
    NODE_TO_PARENT_NODES = 3
    NODE_TO_CHILD_NODES = 4
    NODE_TO_INCOMING_LINKS = 5
    DOCUMENT_TO_TAGS = 8


class GraphEdgeLabel(str, Enum):
    # FIXME: Implement the "implements" and "is implemented by" relationships,
    #        connecting:
    #        - requirements with source files
    #        - test cases with source files.
    IMPLEMENTS = "implements"
    IS_IMPLEMENTED_BY = "is implemented by"

    # The verifies relationship is automatically established between
    # requirements and test cases, when a test case is linked to a requirement.
    VERIFIES = "verifies"
    IS_VERIFIED_BY = "is verified by"

    # The "is result of" relationship is automatically established between
    # test cases and test results, when a test result is linked to a test case.
    IS_RESULT_OF = "is result of"
    HAS_RESULT = "has result"

    # The "satisfies" relationship is automatically established between
    # requirements and test results in a special case when a user project
    # has no autogenerated test case nodes.
    SATISFIES = "satisfies"
    IS_SATISFIED_BY = "is satisfied by"

    def __str__(self) -> str:
        return self.value
