"""Generate .claude/skills/*/SKILL.md pointer stubs from developer/skills/.

developer/skills/ holds the real, git-tracked skill content so it can be
read by any agent/tool. .claude/ is gitignored in this repo, so each
developer/agent regenerates the small SKILL.md stubs Claude Code needs for
skill discovery by running this script locally:

    python developer/skills/install_skills.py

Convention this script relies on: each skill lives in its own directory
under developer/skills/, and its main file is named SKILL.md, e.g.
developer/skills/release-notes/SKILL.md. Any other files in that directory
are supporting material the main file may reference; they are not copied
or parsed here.

Safe to re-run any time: it regenerates all stubs deterministically and
removes stale stubs for skills that no longer exist in developer/skills/,
but only removes directories under .claude/skills/ whose SKILL.md was
itself generated by this script (marked with POINTER_MARKER below), so it
never touches a skill someone authored directly under .claude/skills/.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SKILLS_SRC = REPO_ROOT / "developer" / "skills"
SKILLS_DST = REPO_ROOT / ".claude" / "skills"

POINTER_MARKER = "<!-- generated by developer/skills/install_skills.py -->"

STUB_BODY_TEMPLATE = """{marker}

This is a pointer file, not the skill itself. The actual instructions (and
any supporting files it references) live outside `.claude/` (which is
gitignored in this repo) so they are tracked in git and reusable by other
agents/tools.

Read `developer/skills/{name}/SKILL.md` in full and follow it, including
any sibling files in that directory it points to.
"""


def extract_frontmatter(text: str) -> str | None:
    if not text.startswith("---"):
        return None
    lines = text.splitlines(keepends=True)
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return "".join(lines[: index + 1])
    return None


def install_skill(skill_dir: Path) -> str | None:
    name = skill_dir.name
    main_file = skill_dir / "SKILL.md"
    if not main_file.is_file():
        print(f"skip {name}: no {main_file.relative_to(REPO_ROOT)}")
        return None

    frontmatter = extract_frontmatter(main_file.read_text())
    if frontmatter is None:
        print(f"skip {name}: {main_file.relative_to(REPO_ROOT)} has no frontmatter")
        return None

    stub_dir = SKILLS_DST / name
    stub_dir.mkdir(parents=True, exist_ok=True)
    stub_path = stub_dir / "SKILL.md"
    stub_path.write_text(
        frontmatter + "\n" + STUB_BODY_TEMPLATE.format(marker=POINTER_MARKER, name=name)
    )
    print(f"wrote {stub_path.relative_to(REPO_ROOT)}")
    return name


def remove_stale_stubs(installed_names: set[str]) -> None:
    if not SKILLS_DST.is_dir():
        return
    for stub_dir in SKILLS_DST.iterdir():
        if not stub_dir.is_dir() or stub_dir.name in installed_names:
            continue
        stub_path = stub_dir / "SKILL.md"
        if stub_path.is_file() and POINTER_MARKER in stub_path.read_text():
            import shutil

            shutil.rmtree(stub_dir)
            print(f"removed stale {stub_dir.relative_to(REPO_ROOT)}")


def main() -> None:
    if not SKILLS_SRC.is_dir():
        raise SystemExit(f"{SKILLS_SRC} not found")

    installed = set()
    for skill_dir in sorted(p for p in SKILLS_SRC.iterdir() if p.is_dir()):
        name = install_skill(skill_dir)
        if name is not None:
            installed.add(name)

    remove_stale_stubs(installed)


if __name__ == "__main__":
    main()
