"""
Generate Claude and Codex skill pointer stubs from developer/skills/.

developer/skills/ holds the real, git-tracked skill content so it can be
read by any agent/tool. The agent-specific directories are gitignored in
this repo, so each developer/agent regenerates the small SKILL.md stubs
Claude Code and Codex need for skill discovery by running this script locally:

    python developer/skills/install_skills.py

Convention this script relies on: each skill lives in its own directory
under developer/skills/, and its main file is named SKILL.md, e.g.
developer/skills/release-notes/SKILL.md. Any other files in that directory
are supporting material the main file may reference; they are not copied
or parsed here.

Safe to re-run any time: it regenerates all stubs deterministically and
removes stale stubs for skills that no longer exist in developer/skills/,
but only removes directories whose SKILL.md was itself generated by this
script (marked with POINTER_MARKER below), so it never touches a skill
someone authored directly in an agent-specific directory.
"""

import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SKILLS_SRC = REPO_ROOT / "developer" / "skills"
SKILLS_DESTINATIONS = (
    REPO_ROOT / ".claude" / "skills",
    REPO_ROOT / ".agents" / "skills",
)

POINTER_MARKER = "<!-- generated by developer/skills/install_skills.py -->"

STUB_BODY_TEMPLATE = """{marker}

This is a pointer file, not the skill itself. The actual instructions and
any supporting files they reference live under `developer/skills/`, so they
are tracked in git and reusable by other agents/tools.

Read `developer/skills/{name}/SKILL.md` in full and follow it, including
any sibling files in that directory it points to.
"""


def extract_frontmatter(text: str) -> str | None:
    if not text.startswith("---"):
        return None
    lines = text.splitlines(keepends=True)
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return "".join(lines[: index + 1])
    return None


def install_skill(skill_dir: Path, skills_dst: Path) -> str | None:
    name = skill_dir.name
    main_file = skill_dir / "SKILL.md"
    if not main_file.is_file():
        print(f"skip {name}: no {main_file.relative_to(REPO_ROOT)}")  # noqa: T201
        return None

    frontmatter = extract_frontmatter(main_file.read_text())
    if frontmatter is None:
        print(  # noqa: T201
            f"skip {name}: {main_file.relative_to(REPO_ROOT)} has no frontmatter"
        )
        return None

    stub_dir = skills_dst / name
    stub_dir.mkdir(parents=True, exist_ok=True)
    stub_path = stub_dir / "SKILL.md"
    stub_path.write_text(
        frontmatter
        + "\n"
        + STUB_BODY_TEMPLATE.format(marker=POINTER_MARKER, name=name)
    )
    print(f"wrote {stub_path.relative_to(REPO_ROOT)}")  # noqa: T201
    return name


def remove_stale_stubs(skills_dst: Path, installed_names: set[str]) -> None:
    if not skills_dst.is_dir():
        return
    for stub_dir in skills_dst.iterdir():
        if not stub_dir.is_dir() or stub_dir.name in installed_names:
            continue
        stub_path = stub_dir / "SKILL.md"
        if stub_path.is_file() and POINTER_MARKER in stub_path.read_text():
            shutil.rmtree(stub_dir)
            print(f"removed stale {stub_dir.relative_to(REPO_ROOT)}")  # noqa: T201


def main() -> None:
    if not SKILLS_SRC.is_dir():
        raise SystemExit(f"{SKILLS_SRC} not found")

    skill_dirs = sorted(
        path
        for path in SKILLS_SRC.iterdir()
        if path.is_dir() and (path / "SKILL.md").is_file()
    )
    for skills_dst in SKILLS_DESTINATIONS:
        installed = set()
        for skill_dir in skill_dirs:
            name = install_skill(skill_dir, skills_dst)
            if name is not None:
                installed.add(name)

        remove_stale_stubs(skills_dst, installed)


if __name__ == "__main__":
    main()
