import os
from pathlib import Path

from fastapi.testclient import TestClient

from strictdoc.commands.server_config import ServerCommandConfig
from strictdoc.core.project_config import ProjectConfig, ProjectConfigLoader
from strictdoc.server.app import create_app

PATH_TO_THIS_TEST_FOLDER = os.path.dirname(os.path.abspath(__file__))
PATH_TO_CONFIG = os.path.join(PATH_TO_THIS_TEST_FOLDER, "strictdoc_config.py")
DOCUMENT_MID = "c2d4542d5f1741c88dfcb4f68ad7dcbd"
REQUIREMENT_MID = "3bd0162dd6d242a19324ab8415190970"


def test_upload_asset_rejects_autogenerated_node(tmp_path: Path) -> None:
    server_config = ServerCommandConfig(
        debug=False,
        command="server",
        input_path=PATH_TO_THIS_TEST_FOLDER,
        output_path=str(tmp_path / "output"),
        config=PATH_TO_CONFIG,
        reload=False,
        host="127.0.0.1",
        port=8001,
    )
    project_config: ProjectConfig = (
        ProjectConfigLoader.load_using_server_config(server_config)
    )
    client = TestClient(create_app(project_config=project_config))

    response = client.post(
        (
            "/actions/document/upload_asset"
            f"?document_mid={DOCUMENT_MID}"
            f"&requirement_mid={REQUIREMENT_MID}"
        ),
        files={
            "uploaded_files": (
                "picture.svg",
                b'<svg xmlns="http://www.w3.org/2000/svg"/>',
                "image/svg+xml",
            )
        },
    )

    assert response.status_code == 400
    assert response.json() == {
        "detail": (
            "Asset upload is disabled for autogenerated (=read-only) nodes."
        )
    }
    assert not (Path(PATH_TO_THIS_TEST_FOLDER) / "_assets").exists()
