from jinja2.runtime import LoopContext, Macro, Markup, Namespace, TemplateNotFound, TemplateReference, TemplateRuntimeError, Undefined, escape, identity, internalcode, markup_join, missing, str_join
name = 'components/node/node_controls/index.jinja'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    concat = environment.concat
    cond_expr_undefined = Undefined
    if 0: yield None
    l_0_sdoc_entity = resolve('sdoc_entity')
    l_0_view_object = resolve('view_object')
    pass
    yield '\n\n\n<sdoc-node-controls>\n\n  '
    if (context.call(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'get_type_string')) == 'document'):
        pass
        yield '\n  <a\n  '
        if context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'can_edit_document'), environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document')):
            pass
            yield '\n    href="/actions/document/edit_config?document_mid='
            yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
            yield '"\n    class="action_button"\n    data-turbo-action="replace"\n    data-turbo="true"\n    title="Edit title and meta"\n    data-testid="document-edit-config-action"\n  '
        else:
            pass
            yield '\n    title="Editing is disabled for autogenerated documents"\n    class="action_button action_button--disabled"\n    data-testid="document-edit-config-action-disabled"\n  '
        yield '\n  >'
        template = environment.get_template('icons/ico16_edit.svg', 'components/node/node_controls/index.jinja')
        gen = template.root_render_func(template.new_context(context.get_all(), True, {}))
        try:
            for event in gen:
                yield event
        finally: gen.close()
        yield '</a>'
    if (context.call(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'get_type_string')) != 'document'):
        pass
        if (not environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'is_root_included_document')):
            pass
            yield '\n  <a\n    '
            if context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'can_edit_node'), (undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity)):
                pass
                yield '\n    href="/actions/document/edit_'
                yield escape(context.call(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'get_type_string')))
                yield '?node_id='
                yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
                yield '&context_document_mid='
                yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
                yield '"\n    class="action_button"\n    data-turbo-action="replace"\n    data-turbo="true"\n    title="Edit"\n    data-testid="node-edit-action"\n    '
            else:
                pass
                yield '\n    title="Editing is disabled for autogenerated nodes"\n    class="action_button action_button--disabled"\n    data-testid="node-edit-action-disabled"\n    '
            yield '\n  >'
            template = environment.get_template('icons/ico16_edit.svg', 'components/node/node_controls/index.jinja')
            gen = template.root_render_func(template.new_context(context.get_all(), True, {}))
            try:
                for event in gen:
                    yield event
            finally: gen.close()
            yield '</a>\n  <a\n    '
            if context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'can_delete_node'), (undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity)):
                pass
                yield '\n    href="/actions/document/delete_'
                yield escape(context.call(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'get_type_string')))
                yield '?node_id='
                yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
                yield '&context_document_mid='
                yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
                yield '"\n    class="action_button"\n    data-turbo-method="delete"\n    data-turbo="true"\n    title="Delete"\n    data-testid="node-delete-action"\n    '
            else:
                pass
                yield '\n    title="Deleting is disabled for autogenerated nodes"\n    class="action_button action_button--disabled"\n    data-testid="node-delete-action-disabled"\n    '
            yield '\n  >'
            template = environment.get_template('icons/ico16_delete.svg', 'components/node/node_controls/index.jinja')
            gen = template.root_render_func(template.new_context(context.get_all(), True, {}))
            try:
                for event in gen:
                    yield event
            finally: gen.close()
            yield '</a>\n  '
        else:
            pass
            yield '\n    <a\n      href="/actions/document/edit_included_document?document_mid='
            yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
            yield '&context_document_mid='
            yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
            yield '"\n      class="action_button"\n      data-turbo-action="replace"\n      data-turbo="true"\n      title="Edit"\n      data-testid="node-edit-action"\n    >'
            template = environment.get_template('icons/ico16_edit.svg', 'components/node/node_controls/index.jinja')
            gen = template.root_render_func(template.new_context(context.get_all(), True, {}))
            try:
                for event in gen:
                    yield event
            finally: gen.close()
            yield '</a>\n  '
        yield '\n'
    yield '\n\n  '
    if ((context.call(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'get_type_string')) != 'document') and (not environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'is_root_included_document'))):
        pass
        yield '<a\n    '
        if context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'can_move_node_across_documents'), (undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity)):
            pass
            yield '\n    href="/actions/document/show_move_node?node_mid='
            yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
            yield '"\n    class="action_button"\n    data-turbo-action="replace"\n    data-turbo="true"\n    title="Move"\n    data-testid="node-move-action"\n    '
        elif context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'node_subtree_has_image'), (undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity)):
            pass
            yield '\n    title="Moving nodes with images is not supported yet"\n    class="action_button action_button--disabled"\n    data-testid="node-move-action-disabled"\n    '
        elif context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'node_subtree_has_autogenerated_content'), (undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity)):
            pass
            yield '\n    title="Moving autogenerated nodes is disabled"\n    class="action_button action_button--disabled"\n    data-testid="node-move-action-disabled"\n    '
        else:
            pass
            yield '\n    title="Moving is disabled for this node"\n    class="action_button action_button--disabled"\n    data-testid="node-move-action-disabled"\n    '
        yield '\n  >'
        template = environment.get_template('icons/ico16_move_node.svg', 'components/node/node_controls/index.jinja')
        gen = template.root_render_func(template.new_context(context.get_all(), True, {}))
        try:
            for event in gen:
                yield event
        finally: gen.close()
        yield '</a>'
    if (context.call(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'get_type_string')) == 'requirement'):
        pass
        yield '<a\n    '
        if context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'can_clone_node'), (undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity)):
            pass
            yield '\n    href="/actions/document/clone_requirement?reference_mid='
            yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
            yield '&context_document_mid='
            yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
            yield '"\n    class="action_button"\n    \n    \n    data-turbo="true"\n    title="Clone"\n    data-testid="node-clone-action"\n    '
        else:
            pass
            yield '\n    title="Clone is disabled for autogenerated documents"\n    class="action_button action_button--disabled"\n    data-testid="node-clone-action-disabled"\n    '
        yield '\n  >'
        template = environment.get_template('icons/ico16_copy.svg', 'components/node/node_controls/index.jinja')
        gen = template.root_render_func(template.new_context(context.get_all(), True, {}))
        try:
            for event in gen:
                yield event
        finally: gen.close()
        yield '</a>'
    if ((context.call(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'get_type_string')) != 'document') or (not environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'section_contents'))):
        pass
        if context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'can_add_node'), (undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity)):
            pass
            yield '\n  \n  \n  <sdoc-menu\n    class="add_node"\n  >\n  \n    <sdoc-menu-handler\n      data-dropdown-handler\n      aria-expanded="false"\n      aria-controls="add-node-menu-'
            yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
            yield '"\n    >\n      <a\n        class="action_button"\n        title="Add node"\n        data-testid="node-menu-handler"\n      >'
            template = environment.get_template('icons/ico16_add.svg', 'components/node/node_controls/index.jinja')
            gen = template.root_render_func(template.new_context(context.get_all(), True, {}))
            try:
                for event in gen:
                    yield event
            finally: gen.close()
            yield '</a>\n    </sdoc-menu-handler>\n\n    <sdoc-menu-list>\n      <menu\n        id="add-node-menu-'
            yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
            yield '"\n        aria-hidden="true"\n      >\n        <header>Add node</header>\n\n        '
            if (context.call(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'get_type_string')) == 'document'):
                pass
                yield '\n\n          '
                for l_1_element_ in context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'get_grammar_elements')):
                    _loop_vars = {}
                    pass
                    yield '\n            \n            <li class="sdoc-menu-actions-group">'
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield ':</li>\n\n            \n            <li></li>\n            <li></li>\n            <li>\n              <a\n                  href="/actions/document/new_requirement?reference_mid='
                    yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
                    yield '&whereto=child&element_type='
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield '&context_document_mid='
                    yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
                    yield '"\n                  data-turbo-action="replace"\n                  data-turbo="true"\n                  title="Add first child '
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield '"\n                  data-testid="node-add-'
                    yield escape(context.call(environment.getattr(l_1_element_, 'get_tag_lower'), _loop_vars=_loop_vars))
                    yield '-first-action"\n                >'
                    template = environment.get_template('icons/ico16_add_child.svg', 'components/node/node_controls/index.jinja')
                    gen = template.root_render_func(template.new_context(context.get_all(), True, {'element_': l_1_element_}))
                    try:
                        for event in gen:
                            yield event
                    finally: gen.close()
                    yield '</a>\n            </li>'
                l_1_element_ = missing
            if (context.call(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'get_type_string')) == 'section'):
                pass
                yield '\n          '
                for l_1_element_ in context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'get_grammar_elements')):
                    _loop_vars = {}
                    pass
                    yield '\n            <li class="sdoc-menu-actions-group">'
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield ':</li>\n\n            \n            <li>\n              <a\n                href="/actions/document/new_requirement?reference_mid='
                    yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
                    yield '&whereto=before&element_type='
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield '&context_document_mid='
                    yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
                    yield '"\n                data-turbo-action="replace"\n                data-turbo="true"\n                title="Add '
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield ' above"\n                data-testid="node-add-'
                    yield escape(context.call(environment.getattr(l_1_element_, 'get_tag_lower'), _loop_vars=_loop_vars))
                    yield '-above-action"\n              >'
                    template = environment.get_template('icons/ico16_add_above.svg', 'components/node/node_controls/index.jinja')
                    gen = template.root_render_func(template.new_context(context.get_all(), True, {'element_': l_1_element_}))
                    try:
                        for event in gen:
                            yield event
                    finally: gen.close()
                    yield '</a>\n            </li>\n            <li>\n              <a\n                  href="/actions/document/new_requirement?reference_mid='
                    yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
                    yield '&whereto=child&element_type='
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield '&context_document_mid='
                    yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
                    yield '"\n                  data-turbo-action="replace"\n                  data-turbo="true"\n                  title="Add child '
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield '"\n                  data-testid="node-add-'
                    yield escape(context.call(environment.getattr(l_1_element_, 'get_tag_lower'), _loop_vars=_loop_vars))
                    yield '-child-action"\n                >'
                    template = environment.get_template('icons/ico16_add_child.svg', 'components/node/node_controls/index.jinja')
                    gen = template.root_render_func(template.new_context(context.get_all(), True, {'element_': l_1_element_}))
                    try:
                        for event in gen:
                            yield event
                    finally: gen.close()
                    yield '</a>\n            </li>\n            <li>\n              <a\n                href="/actions/document/new_requirement?reference_mid='
                    yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
                    yield '&whereto=after&element_type='
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield '&context_document_mid='
                    yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
                    yield '"\n                data-turbo-action="replace"\n                data-turbo="true"\n                title="Add '
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield ' below"\n                data-testid="node-add-'
                    yield escape(context.call(environment.getattr(l_1_element_, 'get_tag_lower'), _loop_vars=_loop_vars))
                    yield '-below-action"\n              >'
                    template = environment.get_template('icons/ico16_add_below.svg', 'components/node/node_controls/index.jinja')
                    gen = template.root_render_func(template.new_context(context.get_all(), True, {'element_': l_1_element_}))
                    try:
                        for event in gen:
                            yield event
                    finally: gen.close()
                    yield '</a>\n            </li>\n          '
                l_1_element_ = missing
                yield '\n\n        '
            if (context.call(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'get_type_string')) == 'requirement'):
                pass
                yield '\n          '
                for l_1_element_ in context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'get_grammar_elements')):
                    _loop_vars = {}
                    pass
                    yield '\n            <li class="sdoc-menu-actions-group">'
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield ':</li>\n\n            \n            '
                    if (not environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'is_composite')):
                        pass
                        yield '\n              <li></li>\n            '
                    yield '\n            <li>\n              <a\n                href="/actions/document/new_requirement?reference_mid='
                    yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
                    yield '&whereto=before&element_type='
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield '&context_document_mid='
                    yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
                    yield '"\n                data-turbo-action="replace"\n                data-turbo="true"\n                title="Add '
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield ' above"\n                data-testid="node-add-'
                    yield escape(context.call(environment.getattr(l_1_element_, 'get_tag_lower'), _loop_vars=_loop_vars))
                    yield '-above-action"\n              >'
                    template = environment.get_template('icons/ico16_add_above.svg', 'components/node/node_controls/index.jinja')
                    gen = template.root_render_func(template.new_context(context.get_all(), True, {'element_': l_1_element_}))
                    try:
                        for event in gen:
                            yield event
                    finally: gen.close()
                    yield '</a>\n            </li>\n            '
                    if environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'is_composite'):
                        pass
                        yield '\n            <li>\n              <a\n                href="/actions/document/new_requirement?reference_mid='
                        yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
                        yield '&whereto=child&element_type='
                        yield escape(environment.getattr(l_1_element_, 'tag'))
                        yield '&context_document_mid='
                        yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
                        yield '"\n                data-turbo-action="replace"\n                data-turbo="true"\n                title="Add child '
                        yield escape(environment.getattr(l_1_element_, 'tag'))
                        yield '"\n                data-testid="node-add-'
                        yield escape(context.call(environment.getattr(l_1_element_, 'get_tag_lower'), _loop_vars=_loop_vars))
                        yield '-child-action"\n              >'
                        template = environment.get_template('icons/ico16_add_child.svg', 'components/node/node_controls/index.jinja')
                        gen = template.root_render_func(template.new_context(context.get_all(), True, {'element_': l_1_element_}))
                        try:
                            for event in gen:
                                yield event
                        finally: gen.close()
                        yield '</a>\n            </li>\n            '
                    yield '\n            <li>\n              <a\n                href="/actions/document/new_requirement?reference_mid='
                    yield escape(environment.getattr((undefined(name='sdoc_entity') if l_0_sdoc_entity is missing else l_0_sdoc_entity), 'reserved_mid'))
                    yield '&whereto=after&element_type='
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield '&context_document_mid='
                    yield escape(environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'))
                    yield '"\n                data-turbo-action="replace"\n                data-turbo="true"\n                title="Add '
                    yield escape(environment.getattr(l_1_element_, 'tag'))
                    yield ' below"\n                data-testid="node-add-'
                    yield escape(context.call(environment.getattr(l_1_element_, 'get_tag_lower'), _loop_vars=_loop_vars))
                    yield '-below-action"\n              >'
                    template = environment.get_template('icons/ico16_add_below.svg', 'components/node/node_controls/index.jinja')
                    gen = template.root_render_func(template.new_context(context.get_all(), True, {'element_': l_1_element_}))
                    try:
                        for event in gen:
                            yield event
                    finally: gen.close()
                    yield '</a>\n            </li>'
                l_1_element_ = missing
            yield '</menu>\n    </sdoc-menu-list>\n  </sdoc-menu>\n  '
        else:
            pass
            yield '\n  <a\n    title="Adding nodes is disabled for autogenerated content"\n    class="action_button action_button--disabled"\n    data-testid="node-menu-handler-disabled"\n  >'
            template = environment.get_template('icons/ico16_add.svg', 'components/node/node_controls/index.jinja')
            gen = template.root_render_func(template.new_context(context.get_all(), True, {}))
            try:
                for event in gen:
                    yield event
            finally: gen.close()
            yield '</a>\n  '
    yield '</sdoc-node-controls>'

blocks = {}
debug_info = '17=14&21=17&22=20&33=26&41=33&42=35&44=38&45=41&56=51&58=58&59=61&70=71&73=81&79=85&89=94&91=97&92=100&98=102&102=105&111=112&119=119&121=122&122=125&134=133&142=140&143=142&153=145&159=147&164=154&170=156&173=159&175=163&182=165&185=171&186=173&187=175&195=183&197=186&198=190&203=192&206=198&207=200&208=202&212=209&215=215&216=217&217=219&221=226&224=232&225=234&226=236&234=245&236=248&237=252&240=254&245=258&248=264&249=266&250=268&252=275&255=278&258=284&259=286&260=288&265=296&268=302&269=304&270=306&285=318'