from jinja2.runtime import LoopContext, Macro, Markup, Namespace, TemplateNotFound, TemplateReference, TemplateRuntimeError, Undefined, escape, identity, internalcode, markup_join, missing, str_join
name = 'screens/document/table/type_cell.jinja'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    concat = environment.concat
    cond_expr_undefined = Undefined
    if 0: yield None
    l_0_node = resolve('node')
    l_0_view_object = resolve('view_object')
    l_0_delete_name = resolve('delete_name')
    pass
    yield '<td class="content-view-td content-view-td-type">\n  <div class="content-view-td-type__content">\n    <span>'
    yield escape(environment.getattr((undefined(name='node') if l_0_node is missing else l_0_node), 'node_type'))
    yield '</span>\n    <div class="content-view-td-type__actions">'
    if environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'is_running_on_server'):
        pass
        yield '<span class="table-node-delete-action">'
        t_1 = []
        pass
        template = environment.get_template('icons/ico16_delete.svg', 'screens/document/table/type_cell.jinja')
        gen = template.root_render_func(template.new_context(context.get_all(), True, {'delete_name': l_0_delete_name}))
        try:
            for event in gen:
                t_1.append(event)
        finally: gen.close()
        l_0_delete_name = (Markup if context.eval_ctx.autoescape else identity)(concat(t_1))
        context.vars['delete_name'] = l_0_delete_name
        context.exported_vars.add('delete_name')
        if context.call(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'can_delete_node'), (undefined(name='node') if l_0_node is missing else l_0_node)):
            pass
            l_1_delete_href = markup_join(('/actions/table/delete_node?node_id=', environment.getattr((undefined(name='node') if l_0_node is missing else l_0_node), 'reserved_mid'), '&context_document_mid=', environment.getattr(environment.getattr((undefined(name='view_object') if l_0_view_object is missing else l_0_view_object), 'document'), 'reserved_mid'), ))
            pass
            template = environment.get_template('components/button_inline/delete.jinja', 'screens/document/table/type_cell.jinja')
            gen = template.root_render_func(template.new_context(context.get_all(), True, {'delete_href': l_1_delete_href, 'delete_name': l_0_delete_name}))
            try:
                for event in gen:
                    yield event
            finally: gen.close()
            l_1_delete_href = missing
        else:
            pass
            yield '<a\n            class="action_icon action_button--disabled"\n            title="Deleting is disabled for autogenerated content"\n            data-action-type="delete"\n            data-testid="form-delete-action-disabled"\n          >'
            yield escape((undefined(name='delete_name') if l_0_delete_name is missing else l_0_delete_name))
            yield '</a>'
        yield '</span>'
    yield '\n      \n    </div>\n  </div>\n</td>'

blocks = {}
debug_info = '3=15&5=17&8=22&7=28&10=31&15=35&23=45'