from strictdoc.backend.sdoc.models.document import SDocDocument
from strictdoc.backend.sdoc.models.node import SDocNode, SDocNodeField


class ActionPolicy:
    """
    A stateless policy engine that determines what UI actions are allowed
    for a given node based on document context, inclusion state, and source-code origins.
    """

    @staticmethod
    def _is_autogenerated(node: SDocNode, document: SDocDocument) -> bool:
        if getattr(document, "autogen", False):
            return True
        if getattr(node, "autogen", False):
            return True
        return False

    @staticmethod
    def _is_managed_by_source_code(node: SDocNode) -> bool:
        """
        Helper method to check if a node is partially managed by source code.
        """
        # Is the node entirely generated from source code?
        if getattr(node, "autogen", False):
            return True

        # If the node exists in .sdoc, we check if fields were merged from source-files.
        if hasattr(node, "ordered_fields_lookup"):
            for field_list in node.ordered_fields_lookup.values():
                for field in field_list:
                    # If any field did not originate from the document,
                    # the node's content is partially managed by source code...
                    if (
                        hasattr(field, "is_document_origin")
                        and not field.is_document_origin()
                    ):
                        return True

        return False

    # --- Document Level Actions ---------------------------

    @staticmethod
    def can_edit_document(document: SDocDocument) -> bool:
        """
        Determines if the document's root configuration (title, metadata) can be edited.
        """
        # If the entire document is auto-generated, we can't edit it.
        if getattr(document, "autogen", False):
            return False

        # If the document is a physical .sdoc file, its metadata is editable,
        # regardless of whether it contains source-synced nodes inside it.
        return True

    # --- Node Level Actions ---------------------------

    @staticmethod
    def can_edit_node(node: SDocNode, document: SDocDocument) -> bool:
        # Ephemeral test reports/auto-docs cannot be edited at all
        if ActionPolicy._is_autogenerated(node, document):
            return False

        # NOTE: We intentionally DO NOT check for hybrid fields here!
        # If it's a hybrid node, we let them open the form. The field-level
        # UI wrappers will mark the specific input fields that belong to the C-file as read-only.
        return True

    @staticmethod
    def can_delete_node(node: SDocNode, document: SDocDocument) -> bool:
        # Ephemeral/Virtual documents cannot be edited
        if getattr(document, "autogen", False):
            return False

        # Pure source-code nodes and Hybrid nodes cannot be deleted from the UI
        if ActionPolicy._is_managed_by_source_code(node):
            return False

        return True

    @staticmethod
    def can_clone_node(node: SDocNode, document: SDocDocument) -> bool:
        # We cannot clone a source-managed node because the UI cannot write to the C-file.
        # In this sense, the policy is identical to can_delete
        return ActionPolicy.can_delete_node(node, document)

    @staticmethod
    def can_add_node(node: SDocNode, document: SDocDocument) -> bool:
        # Cannot attach manual nodes to volatile, purely autogenerated nodes/docs.
        # If the parent vanishes on the next sync, the children are lost.
        if ActionPolicy._is_autogenerated(node, document):
            return False

        # NOTE: We do not check for source managed fields here.
        # A hybrid node has a permanent anchor in the .sdoc file, so it is safe
        # to attach new manual siblings or children to it.
        return True

    @staticmethod
    def can_move_node(_node: SDocNode, document: SDocDocument) -> bool:
        # Can't move nodes in ephemeral / autogenerated documents.
        if getattr(document, "autogen", False):
            return False

        # But we can move a source-managed node, because the updates is limited
        # to the sdoc document, moving does not require updating the source code.
        return True

    # --- Field Level Actions ---------------------------

    @staticmethod
    def can_edit_field(field: SDocNodeField) -> bool:
        """
        Determine if an individual text field can be edited in the edit form.
        Fields merged from source code (e.g., C or Rust files, ) are read-only.
        """
        # Fields merged from source-code will not be written back, so any changes would be lost.
        # Don't allow edits for these.
        if hasattr(field, "is_document_origin"):
            return field.is_document_origin()
        return True
