name: StrictDoc Docker CI

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.12

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install minimal Python packages
      run: |
        pip install -r requirements.bootstrap.txt

    - name: Build Docker image with PR branch
      run: |
        invoke build-docker \
          --image pr-${{ github.event.pull_request.number }} \
          --source=${{ github.event.pull_request.head.sha }}

    - name: Set permissions for the output folder.
      run: |
        mkdir -p output/ && chmod 777 output/

    - name: Run container and test StrictDoc installation
      run: |
        invoke test-docker \
          --image pr-${{ github.event.pull_request.number }}
